#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cmath>
#include <chrono>
#include <algorithm>
#include "Eigen/Dense"

#include "MPPIController.h"
#include "UDP.h"

#include <nlohmann/json.hpp>
using json = nlohmann::json;

// ---- Configuration (loaded from config.json) ----
double delta_t;
double wheel_base;
double max_steer_abs;
double max_accel_abs;
int    horizon_step_T;
int    number_of_samples_K;
double param_exploration;
double param_lambda;
double param_alpha;

Matrix2d sigma;
Vector4d stage_cost_weight;
Vector4d terminal_cost_weight;

// CBF (obstacle) parameters
float influence_radius;
float cbf_weight;
float decay_rate;

// Vehicle body box for the collision check / CBF (config VEHICLE_FOOTPRINT).
// Shared with every competitor wrapper so all controllers use the SAME car.
double vehicle_width;
double vehicle_length;
double vehicle_safety_margin;

// Obstacles: exact [x,y,r] circles -> MPPI CBF. Read from OBSTACLES_FILE (JSON,
// generated by generate_costmaps.py from scenario.py OBSTACLES), NOT from config.json.
std::vector<Obstacle> config_obstacles;

std::string ref_path_filepath;

// Obstacle costmap grid: reference-path extent +/- GRID_MARGIN, at GRID_RESOLUTION
// metres per cell. Bounds must match generate_costmaps.py exactly. This is an EXTRA
// cost added on top of the analytic CBF (does not replace it); weight 0 disables it.
double      grid_resolution;
double      grid_margin;
std::string obstacle_costmap_filepath;
double      obstacle_costmap_weight;


void ReadConfig() {
    std::ifstream f("config.json");
    json cfg = json::parse(f);

    delta_t             = cfg["delta_t"];
    wheel_base          = cfg["wheel_base"];
    max_steer_abs       = cfg["max_steer_abs"];
    max_accel_abs       = cfg["max_accel_abs"];
    horizon_step_T      = cfg["horizon_step_T"];
    number_of_samples_K = cfg["number_of_samples_K"];
    param_exploration   = cfg["param_exploration"];
    param_lambda        = cfg["param_lambda"];
    param_alpha         = cfg["param_alpha"];

    sigma << cfg["sigma"][0][0], cfg["sigma"][0][1],
             cfg["sigma"][1][0], cfg["sigma"][1][1];

    stage_cost_weight    << cfg["stage_cost_weight"][0],    cfg["stage_cost_weight"][1],
                            cfg["stage_cost_weight"][2],    cfg["stage_cost_weight"][3];
    terminal_cost_weight << cfg["terminal_cost_weight"][0], cfg["terminal_cost_weight"][1],
                            cfg["terminal_cost_weight"][2], cfg["terminal_cost_weight"][3];

    influence_radius = cfg["CBF_PARAMETERS"]["influence_radius"];
    cbf_weight       = cfg["CBF_PARAMETERS"]["cbf_weight"];
    decay_rate       = cfg["CBF_PARAMETERS"]["decay_rate"];

    // Vehicle footprint (same block the competitor wrappers read)
    {
        const auto& fp = cfg["VEHICLE_FOOTPRINT"];
        vehicle_width         = fp.value("width", 1.9);
        vehicle_length        = fp.value("length", 4.5);
        vehicle_safety_margin = fp.value("safety_margin_rate", 1.0);
    }

    ref_path_filepath = cfg["REF_PATH_FILE"];

    // Obstacle costmap: additive EXTRA cost on top of the CBF below (weight 0 = off).
    grid_resolution           = cfg.value("GRID_RESOLUTION", 1.0);
    grid_margin               = cfg.value("GRID_MARGIN", 10.0);
    obstacle_costmap_filepath = cfg.value("OBSTACLE_COSTMAP_FILE", std::string(""));
    obstacle_costmap_weight   = cfg.value("OBSTACLE_COSTMAP_WEIGHT", 0.0);

    // Obstacles for the CBF: exact circles, read from OBSTACLES_FILE (JSON array,
    // generated by generate_costmaps.py from scenario.py OBSTACLES - [x,y,r] or
    // [x,y,w,h] rect). NOT read from config.json anymore.
    config_obstacles.clear();
    std::string obstacles_filepath = cfg.value("OBSTACLES_FILE", std::string(""));
    if (!obstacles_filepath.empty()) {
        std::ifstream of(obstacles_filepath);
        if (!of.is_open()) {
            throw std::runtime_error("can not open obstacles file: " + obstacles_filepath +
                                     " - run generate_costmaps.py first.");
        }
        json obs_arr = json::parse(of);
        for (const auto& o : obs_arr) {
            if (o.size() < 3) continue;
            Obstacle ob;
            ob.x = (float)o[0];
            ob.y = (float)o[1];
            if (o.size() == 3) {
                ob.r = (float)o[2];                             // [x, y, r] circle
            } else {                                            // [x, y, w, h] rectangle
                float w = (float)o[2], h = (float)o[3];
                ob.r = 0.5f * std::sqrt(w * w + h * h);         // circumscribing circle
            }
            config_obstacles.push_back(ob);
        }
    }
}


// Read the reference path CSV (columns: x, y, yaw, v).
MatrixXd loadRefPath(const std::string& filepath) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("can not open CSV file: " + filepath);
    }

    std::vector<std::vector<double>> data;
    std::string line;
    std::getline(file, line);  // skip header

    while (std::getline(file, line)) {
        std::vector<double> row;
        std::stringstream ss(line);
        std::string cell;
        while (std::getline(ss, cell, ',')) {
            row.push_back(std::stod(cell));
        }
        data.push_back(row);
    }
    file.close();

    if (data.empty()) {
        throw std::runtime_error("Cannot read or empty CSV.");
    }

    MatrixXd matrix(data.size(), data[0].size());
    for (size_t i = 0; i < data.size(); ++i)
        for (size_t j = 0; j < data[i].size(); ++j)
            matrix(i, j) = data[i][j];

    // Normalize the path yaw column (index 2) from [0, 2pi] to [-pi, pi] to match the
    // MPPI state yaw (atan2 output); the GPU-side angle-diff expects this range.
    if (matrix.cols() >= 3) {
        const double PI_D = 3.14159265358979323846;
        for (int i = 0; i < matrix.rows(); ++i) {
            double y = matrix(i, 2);
            while (y >  PI_D) y -= 2.0 * PI_D;
            while (y < -PI_D) y += 2.0 * PI_D;
            matrix(i, 2) = y;
        }
    }
    return matrix;
}


// Load a costmap grid CSV (row-major floats, no header) from generate_costmaps.py.
// Returns false if the file is missing or ragged.
bool loadGrid(const std::string& filepath, std::vector<float>& out,
              int& rows, int& cols) {
    std::ifstream file(filepath);
    if (!file.is_open()) return false;

    out.clear();
    rows = 0;
    cols = 0;
    std::string line;
    while (std::getline(file, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string cell;
        int c = 0;
        while (std::getline(ss, cell, ',')) {
            out.push_back(std::stof(cell));
            ++c;
        }
        if (cols == 0)      cols = c;
        else if (c != cols) return false;   // ragged grid
        ++rows;
    }
    return rows > 0 && cols > 0;
}


// ==========================================================================
// BeamNG control loop
//   1) receive the real vehicle state from the Python bridge (UDP)
//   2) compute the optimal control with MPPI
//   3) send the control back to the bridge
// The internal vehicle dynamics are NOT simulated here - real physics run in BeamNG.
// ==========================================================================
void SimulateBeamNG(MPPIController& mppi, SOCKET serverSocket, SOCKADDR_IN destAddr) {
    std::cout << "[BeamNG] Waiting for first state from bridge..." << std::endl;

    StatePacket state_pkt;
    ControlPacket ctrl_pkt;

    // Block until the first state arrives (waits while BeamNG stabilizes).
    if (!receiveStatePacket(serverSocket, state_pkt, 0)) {
        std::cerr << "[BeamNG] Failed to receive first state." << std::endl;
        return;
    }
    std::cout << "[BeamNG] Connected. Starting control loop..." << std::endl;

    int step = 0;
    const int max_steps = 5000;  // safety limit

    // Per-step MPPI solve time (only calc_control_input is timed -> pure compute, no
    // UDP/BeamNG overhead). It is sent to the bridge in each ControlPacket so it lands in
    // the single run_log_<controller>.csv; this vector is just for the console summary.
    std::vector<double> solve_times;

    while (step < max_steps) {
        if (!state_pkt.valid) {
            std::cout << "[BeamNG] Bridge sent stop signal (valid=0). Exiting." << std::endl;
            break;
        }

        State x0;
        x0 << state_pkt.x, state_pkt.y, state_pkt.yaw, state_pkt.v;

        Control u_opt;
        MatrixXd traj;
        double solve_ms = 0.0;
        try {
            auto _t0 = std::chrono::high_resolution_clock::now();
            std::tie(u_opt, traj) = mppi.calc_control_input(x0);
            solve_ms = std::chrono::duration<double, std::milli>(
                std::chrono::high_resolution_clock::now() - _t0).count();
            solve_times.push_back(solve_ms);
        } catch (const std::out_of_range&) {
            std::cout << "[BeamNG] End of path - completed!" << std::endl;
            // reset=1 -> tell the bridge we are done
            ctrl_pkt.time     = state_pkt.time;
            ctrl_pkt.steer    = 0.0;
            ctrl_pkt.accel    = -max_accel_abs;
            ctrl_pkt.solve_ms = 0.0;
            ctrl_pkt.reset    = 1;
            sendControlPacket(serverSocket, destAddr, ctrl_pkt);
            break;
        }

        ctrl_pkt.time     = state_pkt.time;
        ctrl_pkt.steer    = u_opt[0];
        ctrl_pkt.accel    = u_opt[1];
        ctrl_pkt.solve_ms = solve_ms;   // sent to the bridge -> logged in run_log
        ctrl_pkt.reset    = 0;
        sendControlPacket(serverSocket, destAddr, ctrl_pkt);

        if (step % 20 == 0) {
            std::cout << "[" << step << "] pos=(" << state_pkt.x << "," << state_pkt.y
                      << ") yaw=" << state_pkt.yaw << " v=" << state_pkt.v
                      << " | u=(" << u_opt[0] << "," << u_opt[1] << ")" << std::endl;
        }

        // Wait for the next state (5 s timeout).
        if (!receiveStatePacket(serverSocket, state_pkt, 5000)) {
            std::cerr << "[BeamNG] State timeout - did the bridge stop?" << std::endl;
            break;
        }
        step++;
    }

    std::cout << "[BeamNG] Loop finished. Total steps: " << step << std::endl;

    // --- MPPI solve-time summary (mean / median / p95 / max) ---
    if (!solve_times.empty()) {
        std::vector<double> s = solve_times;
        std::sort(s.begin(), s.end());
        double sum = 0.0;
        for (double v : s) sum += v;
        double mean = sum / s.size();
        double median = s[s.size() / 2];
        double p95 = s[(size_t)(0.95 * (s.size() - 1))];
        std::cout << "[TIMING] MPPI solve (ms) over " << s.size() << " steps: "
                  << "mean " << mean << " | median " << median
                  << " | p95 " << p95 << " | max " << s.back()
                  << "  (also per-step in run_log)" << std::endl;
    }
}


int main(int argc, char* argv[]) {
    std::cout << "[INFO] C++ MPPI controller (BeamNG mode)" << std::endl;

    // --- UDP setup (ports optionally overridden by the bridge) ---
    SOCKET serverSocket;
    sockaddr_in destAddr;
    int cpp_listen_port = 5005;
    int py_send_port    = 5006;
    if (argc >= 3) {
        cpp_listen_port = std::stoi(argv[1]);
        py_send_port    = std::stoi(argv[2]);
    }
    if (!setupUDPSender(serverSocket, destAddr, cpp_listen_port, py_send_port)) {
        return 1;
    }
    std::cout << "[INFO] UDP 127.0.0.1:" << cpp_listen_port
              << " -> 127.0.0.1:" << py_send_port << std::endl;

    // --- config + reference path ---
    ReadConfig();

    MatrixXd ref_path;
    try {
        ref_path = loadRefPath(ref_path_filepath);
        std::cout << "[INFO] Reference path: " << ref_path_filepath
                  << "  (" << ref_path.rows() << "x" << ref_path.cols() << ")" << std::endl;
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        cleanupUDPSender(serverSocket);
        return 1;
    }

    // --- MPPI controller (BeamNG runs at 20 Hz, matching delta_t = 0.05 s) ---
    MPPIController mppi(
        delta_t, wheel_base, max_steer_abs, max_accel_abs,
        ref_path, horizon_step_T, number_of_samples_K,
        param_exploration, param_lambda, param_alpha,
        sigma, stage_cost_weight, terminal_cost_weight,
        config_obstacles, influence_radius, cbf_weight, decay_rate
    );
    mppi.set_vehicle_footprint(vehicle_width, vehicle_length, vehicle_safety_margin);

    // --- Obstacle costmap: EXTRA cost on top of the CBF (does not replace it) ---
    if (!obstacle_costmap_filepath.empty() && obstacle_costmap_weight > 0.0) {
        std::vector<float> obs_grid;
        int o_rows = 0, o_cols = 0;
        if (loadGrid(obstacle_costmap_filepath, obs_grid, o_rows, o_cols)) {
            // Grid bounds convention must match generate_costmaps.py exactly.
            float x_min = (float)(ref_path.col(0).minCoeff() - grid_margin);
            float y_min = (float)(ref_path.col(1).minCoeff() - grid_margin);
            mppi.set_obstacle_costmap(obs_grid, o_rows, o_cols, (float)grid_resolution,
                                      x_min, y_min, (float)obstacle_costmap_weight);
            std::cout << "[INFO] Obstacle costmap: " << obstacle_costmap_filepath
                      << "  (" << o_rows << "x" << o_cols
                      << ", weight " << obstacle_costmap_weight << ")" << std::endl;
        } else {
            std::cerr << "[WARN] Obstacle costmap unreadable: " << obstacle_costmap_filepath
                      << " - continuing WITHOUT the extra obstacle-costmap term "
                      << "(the analytic CBF is unaffected)." << std::endl;
        }
    }

    // Print the shared MPPI config so a fair comparison (same K/T/dt/L) is visible.
    std::cout << "[CONFIG] MPPI: K=" << number_of_samples_K << " T=" << horizon_step_T
              << " dt=" << delta_t << " L=" << wheel_base
              << " lambda=" << param_lambda << std::endl;
    std::cout << "[CONFIG] footprint: " << vehicle_width << " x " << vehicle_length
              << " m, safety_margin " << vehicle_safety_margin << std::endl;

    SimulateBeamNG(mppi, serverSocket, destAddr);

    cleanupUDPSender(serverSocket);
    return 0;
}
